name: Build and deploy Java Azure Functions

env:
  AZURE_FUNCTIONAPP_NAME: cloud-groep22-fitapp-functions
  JAVA_VERSION: '21'
  PACKAGE_DIRECTORY: './cloud-groep22_functions'

on:
  push:
    branches:
      - master
    paths:
      - 'cloud-groep22_functions/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'microsoft'
          cache: 'maven'

      - name: Build with Maven
        run: |
          cd ${{ env.PACKAGE_DIRECTORY }}
          mvn clean package -DskipTests

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: azure-functions-app
          path: '${{ env.PACKAGE_DIRECTORY }}/target/azure-functions/'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: 'https://${{ env.AZURE_FUNCTIONAPP_NAME }}.azurewebsites.net'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: azure-functions-app

      - name: Deploy to Azure Functions
        id: deploy-to-functions
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          slot-name: 'Production'
          package: '${{ env.AZURE_FUNCTIONAPP_NAME }}'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_645F302572EC4514807278EAAD82FF55 }}