name: deploy-azure-functions

on:
  push:
    branches:
      - master
    paths:
      - 'cloud-groep22_functions/**'
  workflow_dispatch:

env:
  JAVA_VERSION: '21'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'microsoft'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build Azure Functions
        run: |
          cd cloud-groep22_functions
          mvn clean package -DskipTests
          mvn azure-functions:package
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: fitapp-functions
          path: 'cloud-groep22_functions/target/azure-functions/*.jar'


  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-functionapp.outputs.functionapp-url }}

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: fitapp-functions

      - name: Deploy to Azure Function App
        uses: azure/functions-action@v1
        id: deploy-to-functionapp
        with:
          app-name: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
          package: '${{ github.workspace }}/cloud-groep22_functions/target/azure-functions/*.jar'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_645F302572EC4514807278EAAD82FF55 }}