name: deploy-azure-functions

on:
  push:
    branches:
      - master
    paths:
      - 'cloud-groep22_functions/**'
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_NAME: cloud-groep22-fitapp-functions
  PACKAGE_DIRECTORY: './cloud-groep22_functions'
  JAVA_VERSION: '21'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'microsoft'

      - name: 'Cache Maven dependencies'
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: 'Restore Project Dependencies Using Maven'
        shell: bash
        run: |
          cd ${{ env.PACKAGE_DIRECTORY }}
          mvn clean package -DskipTests

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          slot-name: 'Production'
          package: '${{ env.PACKAGE_DIRECTORY }}'
          respect-pom-xml: true
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_645F302572EC4514807278EAAD82FF55 }}