name: upload-static-site

on:
  push:
    branches:
      - master
    paths:
      - 'cloud-groep22_frontend/**'
  workflow_dispatch:

jobs:
  upload-static-site:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'cloud-groep22_frontend/package-lock.json'

      - name: Run Upload Script
        run: |
          chmod +x ./upload-site-blob.sh
          ./upload-site-blob.sh
        env:
          AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
          AZURE_STORAGE_CONTAINER: ${{ secrets.AZURE_STORAGE_CONTAINER }}
          AZURE_STORAGE_SAS_TOKEN: ${{ secrets.AZURE_STORAGE_SAS_TOKEN }}